### ISSUE TITLE
yubioauth hangs on "reading credentials" 

### ISSUE THREAD

**Issue by DarkDimius** [Yubico/yubioath-desktop#138]
I've downloaded the updated version(4.0.0): now It hangs on "reading credentials".
That's the same yubikey& machine as in https://github.com/Yubico/yubioath-desktop/issues/70

**Comment by dagheyman** [comment]
So still OSX Yosemite? Did you try running [this package](https://github.com/Yubico/ifd-yubico)? Shouldn't be needed if you are available to list the applets but worth a try.

**Comment by DarkDimius** [comment]
It's now El Capitan.
I'm able to list applets.
The problem seem only to happen after some time of running the laptop.
If I reboot the laptop I can use yubioauth for some time, but then it stops working again.

**Comment by njl07** [comment]
Same problem for me, the latest version of authenticator and it hangs on "reading credentials".

<img width="297" alt="capture d ecran 2017-03-25 a 16 28 10" src="https://cloud.githubusercontent.com/assets/1673977/24323589/3f7077de-1178-11e7-848c-a1f7e43228cc.png">

If I use previous version, all is fine and if I reboot my Mac, it's always same problem.

**Comment by dagheyman** [comment]
> If I reboot the laptop I can use yubioauth for some time, but then it stops working again.
How about removing and re-inserting the YubiKey? Does that have any effect?

**Comment by DarkDimius** [comment]
@dagheyman, for me, removing the YubiKey and plugging in different usb port doesn't help.

**Comment by dagheyman** [comment]
I just released version [4.0.1](https://developers.yubico.com/yubioath-desktop/Releases/) which should have some improved error logging. Could you try installing this version and start the app from the terminal to see if there is any output when the error happens?

**Comment by DarkDimius** [comment]
@dagheyman 
```
dark@reco /Applications/Yubico Authenticator.app $ ./Contents/MacOS/yubioath-desktop
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 23, in wrapped
    return json.dumps(f(*(json.loads(a) for a in args)))

  File "qrc:///py/yubikey.py", line 135, in get_oath_id
    controller = OathController(dev.driver)

AttributeError: 'NoneType' object has no attribute 'driver'

qml: qrc:///qml/YubiKey.qml:128: Error: Cannot assign [undefined] to QString

```

Gui says "reading credentials"

**Comment by njl07** [comment]
What's the status on this issue?

**Comment by dagheyman** [comment]
I can't reproduce this on my mac, so I'm not sure why it's happening. It seems to be some problem at the CCID level. For debugging purposes, would you mind running the [YubiKey Manager command line tool](https://developers.yubico.com/yubikey-manager/), `ykman info` both when authenticator is working and when it is at the broken stage?

You can also try `ykman oath code` to see if the OATH part works well.

**Comment by DarkDimius** [comment]
@dagheyman, unfotrunately, I can't install `ykman` installation instructions fail on my machine:
https://gist.github.com/DarkDimius/959e365ed3b379b87830a4ce5b1b390a.

I do have a standalone ykinfo command though. 
If it does the same thing here's output for `ykinfo -a`:
```
serial: ****** // removed for privacy reasons
serial_hex: ****** // removed for privacy reasons
serial_modhex: ****** // removed for privacy reasons
version: 3.3.7
touch_level: 1547
programming_sequence: 3
slot1_status: 1
slot2_status: 1
vendor_id: 1050
product_id: 116
```

**Comment by DarkDimius** [comment]
The output stays the same when yubioath-desktop stops working.

**Comment by dagheyman** [comment]
Ah, could you try `pip3 install yubikey-manager` instead? (Instructions should be updated probably).

The `ykinfo` tool doesn't give much in this case, because it is only looking at the OTP/YubiKey Slot part of the YubiKey, but authenticator is using the CCID / Smart card side.

**Comment by DarkDimius** [comment]
@dagheyman, the error would stay the same. Using `pip` on non-modified macbook is not guaranteed. It tries to install packages in protected folders, that you can't modifiy on MacOS.
I figured out, the correct command would be:
```
pip3 install --user yubikey-manager
```
It would install ykman in `/Users/dark/Library/Python/2.7/bin`, which isn't included in $PATH by default.

Anyhow, here's the output:

```
./ykman info
Device name: YubiKey NEO
Serial number: XXXXXXXX // removed for privacy reasons
Firmware version: 3.3.7
Enabled connection(s): OTP+U2F+CCID

Device capabilities:
    OTP:	Enabled
    U2F:	Enabled
    CCID:	Enabled
    OPGP:	Enabled
    PIV:	Enabled
    OATH:	Enabled

 ./ykman oath code
Usage: ykman [OPTIONS] COMMAND [ARGS]...

Error: Failed connecting to the YubiKey.
```

**Comment by dagheyman** [comment]
Ok. If you do `ykman mode c` to enable CCID mode only, and then do `ykman info` again, can you still list the capabilities?

This will disable u2f and otp, so to restore your key do `ykman mode c+o+u`.

**Comment by DarkDimius** [comment]
> Ok. If you do `ykman mode c` to enable CCID mode only, and then do ykman info again, can you still list the capabilities?


After running this command on my machine, I can't detect yubikey anymore after re-inserting it.
Trying reboot to see if it helps.

**Comment by DarkDimius** [comment]
Rebooting helped. Now the yubikey is detected
```
Device name: YubiKey NEO
Serial number: XXXXXXXX // removed for privacy reasons
Firmware version: 3.3.7
Enabled connection(s): CCID

Device capabilities:
    OTP:	Disabled
    U2F:	Disabled
    CCID:	Enabled
    OPGP:	Enabled
    PIV:	Enabled
    OATH:	Enabled
```

yubioath now asks for password and hangs on "reading credentials". It didn't ask for password before.

**Comment by DarkDimius** [comment]
Now the funny part. Authenticator version 4.0.1 hangs, while 3.0.1 works.

**Comment by dagheyman** [comment]
Some ideas:
- make sure the smart card is not locked by any other application such as a VM or gpg-agent. Don't run 3.0.1 and 4.0.1 of Authenticator simultaneously (including the systray).
- what happens when you enter the correct password? Can you access your codes?
- note that 3.0.1 mixes "Slot mode" and "CCID mode", showing OATH credentials stored on the OTP side together with credentials stored on the CCID side. In 4.0.1 you have to explicitly choose mode under settings. When you see credentials, are they named "Yubikey Slot.." or do they have custom names?

**Comment by DarkDimius** [comment]
>    make sure the smart card is not locked by any other application such as a VM or gpg-agent. Don't run 3.0.1 and 4.0.1 of Authenticator simultaneously (including the systray).

Yes, I've made sure that only one was running at the time. 

>    note that 3.0.1 mixes "Slot mode" and "CCID mode", showing OATH credentials stored on the OTP side together with credentials stored on the CCID side. In 4.0.1 you have to explicitly choose mode under settings. When you see credentials, are they named "Yubikey Slot.." or do they have custom names?

I don't have OATH credential in slots, only in CCIDs. Slots are used for different passwords\etc.

 >   what happens when you enter the correct password? Can you access your codes?

In 3.0.1 - yes, after reboot. In 4.0.1 - no, it hangs on "reading credentials" after asking for password. 

Here's the output of 4.0.1 in command line: https://gist.github.com/DarkDimius/a81b84ec6bd35af076665f4e629b5d2c

**Comment by dagheyman** [comment]
> Here's the output of 4.0.1 in command line: https://gist.github.com/DarkDimius/a81b84ec6bd35af076665f4e629b5d2c

Thank you very much for that log, so it seems to be some issue with how the python library cryptography links to openssl. We don't use it in 3.0.1, so that would explain why that version works somewhat better. Will look into it and try to figure out what is going on.

**Comment by kun-zhou** [comment]
Same issue here, but `ykman auth code` seems to work without a problem.

**Comment by icawebdesign** [comment]
I'm experiencing the same thing (hanging on reading credentials) for 4.1.0 on Mac El Capitan. 3.1.0b working fine with same key.

**Comment by dagheyman** [comment]
Still investigating this, but could you try if doing `brew install openssl` makes any difference?

**Comment by dagheyman** [comment]
Also interested in how this [development build](https://s3-eu-west-1.amazonaws.com/yubico-builds/yubioath-desktop/yubioath-desktop-4.1.1-dev.app.zip) behaves, please try it out if you have the possibility.

**Comment by iltempo** [comment]
I had the same issue with 4.1.0. For me, the development build fixed the issue. Openssl is installed all the time via brew on my systems. Thank you.

**Comment by icawebdesign** [comment]
Can also confirm that the dev build works for me too 👍

**Comment by dagheyman** [comment]
Closing, should be fixed in 4.1.1.

**Comment by DarkDimius** [comment]
@dagheyman, just had a change to try out 4.1.1-dev build.
Unfortunately, it didn't fix the issue for me. It still hangs on "reading credentials"

Log:
```
dark@reco ~/Downloads/yubioath-desktop-4.1.1-dev.app $ ./Contents/MacOS/yubioath-desktop
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 23, in wrapped
    return json.dumps(f(*(json.loads(a) for a in args)))

  File "qrc:///py/yubikey.py", line 135, in get_oath_id
    controller = OathController(dev.driver)

AttributeError: 'NoneType' object has no attribute 'driver'

qml: qrc:///qml/YubiKey.qml:129: Error: Cannot assign [undefined] to QString
```

**Comment by DarkDimius** [comment]
Should I open a new issue, or would you kindly reopen this one?

**Comment by dagheyman** [comment]
@DarkDimius: Ok, so at least your issue is not related to `libssl.1.0.0.dylib` anymore. Unfortunately I don't have much more to go on right now. Maybe Console.app has some interesting output when you try to start the app? Also, please try with the real 4.1.1 release, even if they shouldn't differ much.

**Comment by DarkDimius** [comment]
@dagheyman, https://gist.github.com/DarkDimius/e45c20069c0e64aae9d1b092640ebd10 - this is the output of Console.app. Hope it helps.

**Comment by dagheyman** [comment]
```
09/05/17 11:38:37.190 appleeventsd[62]: <rdar://problem/11489077> A sandboxed application with pid 42951, "Yubico Authenticator" checked in with appleeventsd, but its code signature could not be read and validated by appleeventsd, and so it cannot receive AppleEvents targeted by name, bundle id, or signature. Install the application in /Applications/ or some other world readable location to resolve this issue. Error=ERROR: #100013  { "NSDescription"="SecCodeCopySigningInformation() returned 100013, -." }  (handleMessage()/appleEventsD.cp #2098) com.apple.root.default-qos
```
So maybe this is a clue, did you it install it outside /Applications/? Could you try installing it in /Applications/ and see if it makes a difference?

**Comment by DarkDimius** [comment]
@dagheyman, unfortunately moving to `/Applications/` did not make a difference.

**Comment by dagheyman** [comment]
@DarkDimius Ok. I managed to reproduce the `09/05/17 11:38:36.000 kernel[0]: failed to parse entitlements for yubioath-desktop[42951]: OSUnserializeXML: syntax error near line 1`, and fixed it by changing the format of a Entitlements.plist file used when code signing.

Could you try this build and see if that part has been resolved on your end as well?
https://yubico-builds.s3-eu-west-1.amazonaws.com/yubioath-desktop/Yubico%20Authenticator-4.1.1-dev2.app.zip

Thanks for all your patience and testing by the way.

**Comment by DarkDimius** [comment]
@dagheyman, thanks for trying to fix the issue! Unfortunately it did not fix the issue

Terminal:
```
dark@reco /Applications/Yubico Authenticator-4.1.1-dev2.app $ ./Contents/MacOS/yubioath-desktop
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 23, in wrapped
    return json.dumps(f(*(json.loads(a) for a in args)))

  File "qrc:///py/yubikey.py", line 135, in get_oath_id
    controller = OathController(dev.driver)

AttributeError: 'NoneType' object has no attribute 'driver'

qml: qrc:///qml/YubiKey.qml:129: Error: Cannot assign [undefined] to QString
```

Console: 
```
09/05/17 13:06:15.651 sandboxd[155]: ([43766]) yubioath-desktop(43766) deny file-read-data /usr/local/Cellar/openssl/1.0.2h_1/lib/libssl.1.0.0.dylib
09/05/17 13:06:15.673 sandboxd[155]: ([43766]) yubioath-desktop(43766) deny file-read-data /usr/local/Cellar/openssl/1.0.2h_1/lib/libssl.1.0.0.dylib
09/05/17 13:06:15.726 sandboxd[155]: ([43766]) yubioath-desktop(43766) deny file-read-data /usr/local/Cellar/openssl/1.0.2h_1/lib/libssl.1.0.0.dylib
```

**Comment by dagheyman** [comment]
@DarkDimius Ok, so the issue with Entitlements seems resolved, that's good at least. Let's try this one: https://yubico-builds.s3-eu-west-1.amazonaws.com/yubioath-desktop/yubioath-desktop-4.1.1.dev3.app.zip
(tweaked the linking to OpenSSL a bit more)

**Comment by DarkDimius** [comment]
@dagheyman, with this version no messages appear in `Console.app`.

Terminal:
```
dark@reco /Applications/yubioath-desktop-4.1.1.dev3.app $ ./Contents/MacOS/yubioath-desktop
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 23, in wrapped
    return json.dumps(f(*(json.loads(a) for a in args)))

  File "qrc:///py/yubikey.py", line 135, in get_oath_id
    controller = OathController(dev.driver)

AttributeError: 'NoneType' object has no attribute 'driver'

qml: qrc:///qml/YubiKey.qml:129: Error: Cannot assign [undefined] to QString
```

**Comment by bezcitu** [comment]
Hi, I'm on Arch Linux and have the same issue:

```
[elliot@fsociety]$ yubioath-desktop 
Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 23, in wrapped\n    return json.dumps(f(*(json.loads(a) for a in args)))\n\n  File \"qrc:///py/yubikey.py\", line 135, in get_oath_id\n    controller = OathController(dev.driver)\n\nAttributeError: 'NoneType' object has no attribute 'driver'\n"
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 23, in wrapped
    return json.dumps(f(*(json.loads(a) for a in args)))

  File "qrc:///py/yubikey.py", line 135, in get_oath_id
    controller = OathController(dev.driver)

AttributeError: 'NoneType' object has no attribute 'driver'

qml: qrc:///qml/YubiKey.qml:129: Error: Cannot assign [undefined] to QString
```

**Comment by DarkDimius** [comment]
FYI: I've just updated to OS X Sierra and I am no longer able to reproduce the issue.

**Comment by dagheyman** [comment]
@DarkDimius I'm sorry we never figured out the root cause of this, but I'm glad it's working for you now. Closing for now.

**Comment by squidpickles** [comment]
I subscribed to this yesterday, because I'm having the same problem on both macOS Sierra and Arch Linux. (The authenticator hangs until I unplug and re-plug the Yubikey.)

Based on the comments here, and my own experience, it sounds like yubioauth doesn't work when `gpg-agent` is in use. If that's the case, I might open another ticket specifically mentioning that incompatibility, as I definitely would want to use both with the same key.

**Comment by dagheyman** [comment]
@squidpickles There is indeed a problem with using gpg-agent and the released version of Yubico Authenticator on macOS. There is code to kill scdaemon, but it fails when run in the sandboxed released version of the app. Here are some issues with some context:

https://github.com/Yubico/yubioath-desktop/issues/89
https://github.com/Yubico/yubikey-manager/issues/15

I'm hoping to resolve this in the next release.

I don't think that this is the issue this thread was originally about though. And I'm not sure about on Arch Linux, not much testing is done on that OS on my side. Feel free to describe what is going on there in a separate issue.

**Comment by EmFl** [comment]
I have the same issue on windows 10, have to unplug my yubikey a random number of times to get it to work... 
yubikey neo manager detects it 100% of the time even when the auth application says reading credentials

**Comment by squidpickles** [comment]
@dagheyman Thanks for the pointers. Those two issues look likely to be the root cause.

The Arch Linux errors follow the same pattern, so I'm guessing it's not anything different here. If, after those are resolved, the problems persist, I can open a new ticket.

**Comment by dagheyman** [comment]
@EmFi & @squidpickles : I'd suggest you open separate issues for your problems, so we can track the different platforms separately. Windows 10 and Linux problems can't be caused by the macOS sandbox, so it must be something else.

**Comment by bezcitu** [comment]
I previously encountered the bug on Arch and upgraded to the git-version. Now the bug is (hopefully) gone, using yubioath 4.1.3.

**Comment by kciredor** [comment]
Hey @bezcitu how's it working out for you? I found this github issue by googling for my problem: arch linux + yubikey (neo) + gpg = oath not working. Running the git version of yubi authenticator.

**Comment by TurnaevEvgeny** [comment]
Same issue here. 3.1.0b works beautifully. Will stick with 3.1.0b for now.
Basically I went through all same steps as DarkDimius did.
All 4.x give me
`/Applications/Yubico Authenticator.app$ ./Contents/MacOS/yubioath-desktop
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 24, in wrapped
    return json.dumps(f(*(json.loads(a) for a in args)))

  File "qrc:///py/yubikey.py", line 136, in get_oath_id
    controller = OathController(dev.driver)

AttributeError: 'NoneType' object has no attribute 'driver'

qml: qrc:///qml/YubiKey.qml:129: Error: Cannot assign [undefined] to QString`
tried almost all 4.x.x, keeps showing me this traceback when the key inserted.
Latest manager has no problems finding the key. 
Tried cloning https://github.com/Yubico/ifd-yubico and `sudo osx-patch-ccid`
Tried running if os.path.isfile(INFO_PLIST_LOCAL): branch from that file separately but it didn't work because it didn't find a file in LIBCCID var.
Tried brew update & install openssl.
Then tried keeping only CCID. Key wasn't connecting. So I rebooted. 
Installed 3.1.0b and it works.
Enabled ykman mode c+o+u and tried 4.x latest and it doesn't with the same traceback. 
So I'll just stick with 3.1

OS X Yosemite 10.10.3 (14D136)
In [2]: platform.mac_ver()
Out[2]: ('10.10.3', ('', '', ''), 'x86_64')

Thanks to everyone in this thread.

**Comment by ia64mail** [comment]
I've got a similar error after upgrading to 4.1.4 on Ubuntu 16.04. It hangs on "reading credentials..." but stack trace is different:
```
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 24, in wrapped\n    return json.dumps(f(*(json.loads(a) for a in args)))\n\n  File \"qrc:///py/yubikey.py\", line 73, in refresh_credentials\n    c.to_dict() for c in self._calculate_all(timestamp, password_key)]\n\n  File \"qrc:///py/yubikey.py\", line 223, in _calculate_all\n    creds = [c for c in creds if not c.hidden]\n\n  File \"qrc:///py/yubikey.py\", line 223, in <listcomp>\n    creds = [c for c in creds if not c.hidden]\n\nAttributeError: 'Credential' object has no attribute 'hidden'\n"
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 24, in wrapped
    return json.dumps(f(*(json.loads(a) for a in args)))

  File "qrc:///py/yubikey.py", line 73, in refresh_credentials
    c.to_dict() for c in self._calculate_all(timestamp, password_key)]

  File "qrc:///py/yubikey.py", line 223, in _calculate_all	
    creds = [c for c in creds if not c.hidden]

  File "qrc:///py/yubikey.py", line 223, in <listcomp>
    creds = [c for c in creds if not c.hidden]

AttributeError: 'Credential' object has no attribute 'hidden'

qml: qrc:///qml/YubiKey.qml:168: TypeError: Cannot read property 'length' of undefined
```

**Comment by dagheyman** [comment]
@ia64mail I think this is the same as #178, could you try a `$ sudo apt upgrade` ?

**Comment by ia64mail** [comment]
@dagheyman Thanks, it works again.

**Comment by tr3buchet** [comment]
I have this same issue with version 4.3.4. After 20 minutes, still says "Reading credentials...". OSX
