### ISSUE TITLE
[Linux] Yubikey not found after activating U2F Module

### ISSUE THREAD

**Issue by raabf** [Yubico/yubioath-desktop#22]
Brief
------

The `Show Code` operation from the systray will fail with `No Yubikey NEO found. Please plugin your Yubikey NEO in one of your USB port.` This occurs sine I activate the U2F Module in my Yubikey NEO.

Reproduce
------------

 1. Plug In your Yubikey
 2. `lsusb` should find your yubikey: `Bus 001 Device 012: ID 1050:0116 Yubico.com`
 3. Start `python2 ./yubicoauthenticator/ui_systray.py`. The Yubico Tray icon should be appear in the tray without errors.

 3.a Alternative: plug in your yubikey here instead in Point 1.
 3.b `lsusb` should find your yubikey: `Bus 001 Device 012: ID 1050:0116 Yubico.com`
 4. A message boy with `No Yubikey NEO found. Please plugin your Yubikey NEO in one of your USB port.` appears
 5. On Console the following will be printed:

 ```
'NoneType' object has no attribute '_cmd_ok'
No smartcard reader found with YubiOath applet
```

 5.a Alternative message on the VM Machine:

 ```
'NoneType' object has no attribute '_cmd_ok'
'Failure to establish context: Service not available.'
```

Notes
------

 + yubioath-desktop still working on windows 8.1 x64 on the same machine
 + The Linux version of yubioath-desktop worked before activation of the U2F module. I'am not to 100% sure if this is related, since I activated the U2F module on windows and only use Windows for a long time afterwards.
 + The *Yubikey Personalization Tool* correctly detects the yubikey

Environment
---------------

### Linux environment

 + Ubuntu 14.04
 + yubioath-desktop 0.1.1

### VM Linux environment

 + Ubuntu 14.04
 + yubioath-desktop 0.1.1
 + more clean and fresh then the other environment

**Comment by raabf** [comment]
Sorry just see the duplicate #15 issue.
